create table ipl_matches (

        id INTEGER Generated by DEFAULT as IDENTITY,
        season varchar(255),
        city varchar(255),
        team1 varchar(255),
        team2 varchar(255),
        date varchar(255),
        target varchar(255),
        winner varchar(255),
        match_type varchar(255),
        result varchar(255),
        result_margin varchar(255),
        player_of_match varchar(255),
        primary key(id)

);